---
- name: Install Memcached
  dnf:
    name: memcached
    state: present

- name: Listen on all interfaces
  lineinfile:
    path: /etc/sysconfig/memcached
    regexp: '^OPTIONS='
    line: 'OPTIONS="-l 0.0.0.0"'

- name: Start memcached
  service:
    name: memcached
    state: started
    enabled: true

- name: Open port
  firewalld:
    port: 11211/tcp
    permanent: yes
    state: enabled
    immediate: yes
