---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Configure vproapp
  copy:
    dest: /etc/nginx/sites-available/vproapp
    content: |
      upstream vproapp {
          server 192.168.23.22:8080;
      }

      server {
          listen 80;
          location / {
              proxy_pass http://vproapp;
          }
      }

- name: Enable vproapp
  file:
    src: /etc/nginx/sites-available/vproapp
    dest: /etc/nginx/sites-enabled/vproapp
    state: link
    force: yes

- name: Remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
